development:
  adapter: postgresql
  encoding: unicode
  database: EmotaApp_development
  pool: 5
  username: postgres
  password: 1314Fa311e

test:
  adapter: postgresql
  encoding: unicode
  database: EmotaApp_test
  pool: 5
  username: postgres
  password: 1314Fa311e

production:
  adapter: postgresql
  encoding: unicode
  database: EmotaApp_production
  pool: 5
  username: postgres
  password: 1314Fa311e
