development:
  adapter: postgresql
  encoding: unicode
  database: EmotaApp_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: EmotaApp_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: EmotaApp_production
  pool: 5
  username: postgres
  password:
