development:
  secret_key_base: #Rake secret
  MICROSOFT_EMOTION_API_KEY:
  SNS_ACCESS_KEY_ID:
  SNS_SECRET_ACCESS_KEY:

test:
  secret_key_base: #Same as development

production:
  secret_key_base: #Production secret
  PUSHER_APP_ID:
  PUSHER_APP_KEY:
  PUSHER_APP_SECRET:
  MICROSOFT_EMOTION_API_KEY:
  SNS_ACCESS_KEY_ID:
  SNS_SECRET_ACCESS_KEY:
